### ISSUE TITLE
my_global.h workaround?

### ISSUE THREAD

**Issue by theofficejackpot** [StirlingMarketingGroup/mysql-trimmean#2]
hi, I am interested in using your function, but in mysql 8, they did away with my_global.h

I get:

```
trimmean.c:12:10: fatal error: my_global.h: No such file or directory
 #include <my_global.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

Any workaround to this, please?

**Comment by BrianLeishman** [comment]
This is interesting, looks like PHP also had this issue with their own extensions, I'll have to look into seeing how they solved it

**Comment by BrianLeishman** [comment]
I removed the parts that relied on `my_global.h`, so it should compile now on installs without it

**Comment by theofficejackpot** [comment]
That worked, I'm good on Ubuntu 18, Mysql 8.  Cheers!
